import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Product from "@/components/slide";
import ProductList from "@/components/productList";
import CategoryList from "@/components/categoryList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const images = [
    {
      url: "/images/orand.jpeg",
      name: "Akwa oche",
      price: "N 7,500",
    },
    {
      url: "/images/silk.jpeg",
      name: "Silk",
      price: "N 9,500",
    },
  ];

  const categories = [
    {
      id: 1,
      logoURL: "/images/categories/fabrics.png",
      name: "Fabrics"
    },
    {
      id: 2,
      logoURL: "/images/categories/hats.png",
      name: "Hats"
    },
    {
      id: 3,
      logoURL: "/images/categories/clothes.png",
      name: "Clothes"
    },
    {
      id: 4,
      logoURL: "/images/categories/hairs.png",
      name: "Hairs"
    },
    {
      id: 5,
      logoURL: "/images/categories/shoes.png",
      name: "Shoes"
    },
    
  ]

  const items = {
    category: "Fabrics",
    products: [
    {
      id: 1,
      url: "/images/products/1.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 2,
      url: "/images/products/2.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 3,
      url: "/images/products/3.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 4,
      url: "/images/products/4.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 5,
      url: "/images/products/5.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 6,
      url: "/images/products/6.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 7,
      url: "/images/products/7.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 8,
      url: "/images/products/8.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 9,
      url: "/images/products/9.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 10,
      url: "/images/products/10.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 11,
      url: "/images/products/11.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 12,
      url: "/images/products/12.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 13,
      url: "/images/products/13.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 14,
      url: "/images/products/14.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 15,
      url: "/images/products/15.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    {
      id: 16,
      url: "/images/products/16.jpeg",
      name: "Plain Silk",
      price: 'N 7,500',
    },
    
  ]
}

  return (
    <>
      <Head>
        <title>JEJ World Classic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainBody}>
        <div className={styles.head}>
          <img className={styles.logo} src="/images/logo.png" alt="logo"></img>
          <div>
            <input placeholder="search"></input>
            <img src="/images/search.png" alt="search"></img>
          </div>
          <img className={styles.cart} src="/images/cart.png" alt="cart"></img>
        </div>
        <div className={styles.hero}>
          <div className="categories">
            <h2>Categories</h2>
            <CategoryList items={categories}/>
          </div>
          <div className="recent">
            <h2>Recent</h2>
            <div className={styles.slider}>
              <Product images={images}></Product>
            </div>
          </div>
          <div className={styles.login}>
            <h2>Login</h2>
            <form>
              <div className={styles.inputFields}>
                <label htmlFor="username">Username</label>
                <input type="text" name="username" />
              </div>
              <br />
              <div className={styles.inputFields}>
                <label htmlFor="password">Password</label>
                <input type="password" name="password" />
              </div>
            </form>
          </div>
          <div className={styles.products}>
            <ProductList items={items}></ProductList>
          </div>
          
        </div>
        
      </main>
    </>
  );
}
